### ISSUE TITLE
stock filter issue

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#638]
hi

I have noticed issues with filters. For example: Parts "A" is setup like stock=2 minimum stock=3. Filter stock level <  minimum stock level is working okay but if you are changing minimum stock to ( for example )1. Filter will show you again parts "A" is below the minimum stock what is not true because minimum stock is already 1 and stock 2. I have checked with demo. 
![issue](https://cloud.githubusercontent.com/assets/13379408/14310966/c1464084-fbdc-11e5-9588-4dac37914254.jpg)

**Comment by felicitus** [comment]
Can you give clear instructions on how to reproduce the issue?

**Comment by mctomaszek** [comment]
hi

Please only change minimum stock level without adding or removing quantity of parts

regards

**Comment by felicitus** [comment]
Honestly I still don't know how to reproduce. A good guide to reproduce things is written like this:

* Navigate to XY
* Click button X
* Go to Y
etc

I did not understand the initial bug report, and as such I'm asking for detailed steps to reproduce.

**Comment by mctomaszek** [comment]
hi

Let's have a check like that. Please only change for example 2N7000 minimum stock level =1000. Then please use a filter stock level< minimum stock. Filter will not show you 2n700 below minimum stock.

regards

**Comment by felicitus** [comment]
That particular filter is only applied when you refresh the parts list, or change category. Can you double-check if the filter is working correctly after you change the category, click apply filter or reload the parts list?

**Comment by mctomaszek** [comment]
hi
I have checked even you are logging off of the system.Refreshing, changing category does not fix problem. Filter will not find that this stock is below minimum till you will add or remove quantity of 2N700. 



regards

**Comment by felicitus** [comment]
I will have a closer look but it may take a few days

**Comment by felicitus** [comment]
I believe the issue is fixed now, can you re-test on the demo system?

**Comment by mctomaszek** [comment]
hi 
on demo still does not work.I have changed minimum stock to 2n7000 to 1000pc and filter can not find it that minimum stock is higher than stock

**Comment by felicitus** [comment]
Can you try again in an hour? I guess that the bugfix didn't arrive on the demo system yet.

**Comment by mctomaszek** [comment]
hi

so far so good...thank you
