### ISSUE TITLE
Exported xlsx cannot be opened in Excel

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#646]
One example:
In main meny click on Edit -> Projects
Click on Export button on the project column side (left side) -> Export grid -> Excel 2007 or later
When trying to open the file in excel (2013) it says that the file is not compatible and cannot be open.

**Comment by felicitus** [comment]
I can confirm the issue.

As a workaround you can use the CSV export until the bug is fixed

**Comment by felicitus** [comment]
The issue should now be solved. Please test against the demo system in one hour.

**Comment by adis1987** [comment]
This fault still presists. In latest version 1.1.0 I still cannot export to excel.

**Comment by felicitus** [comment]
I just double-checked and it works for me opening the .xlsx file in LibreOffice - I don't have MS Excel at hand. Do you receive a particular error message?

**Comment by adis1987** [comment]
I tryed now to open it with google with same result, not working. The message in excel is just that is was possible to open it because it might be broken...

**Comment by nealkfr** [comment]
Just for documentation sake, I have experienced this same issue since first using partkeepr. I am using Office365 and upon opening the download I receive:

Excel cannot open the file 'export.xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.

**Comment by felicitus** [comment]
I was able to reproduce the issue. Unfortunately, there's no quick fix. OpenOffice and LibreOffice can open the sheets just fine - mainly because they interpret the actual contents and not the file extension.

The library we're using for exporting does only support exporting a single sheet and not a workbook, and that's what confuses MS Office.

Rescheduled for 1.3

**Comment by FabPell980** [comment]
Same issue here. The exported file is an XML.
